make sure errors print to &2

diff --git a/floatversion b/floatversion
--- a/floatversion
+++ b/floatversion
@@ -98,7 +98,7 @@ float_version_from_string ()  {
   License: MIT  Copyright (c) Alex Genovese  
   Further Usage/Help/Details @ https://github.com/TuxVinyards/floatversion
 
-"
+"  
   }
 
   local ShowAsCol=
@@ -163,11 +163,11 @@ float_version_from_string ()  {
         NoSortVfallback=1 ; shift ;;
       *) 
         if [[ "$1" == '-'* ]]; then
-          printf "\n\n  ERROR:  '%s'  not recognised \n\n" "$1" 
-          show_help ; return 1
+          printf "\n\n  ERROR:  '%s'  not recognised \n\n" "$1" >&2
+          show_help >&2 ; return 1
         elif [[ $InputText ]]; then
-          printf "\n\n  ERROR: QUOTED Input String or Text File Name should be given only once \n\n" 
-          show_help ; return 1
+          printf "\n\n  ERROR: QUOTED Input String or Text File Name should be given only once \n\n" >&2
+          show_help >&2 ; return 1
         else
           InputText="$1" ; shift 
         fi ;;
@@ -180,8 +180,8 @@ float_version_from_string ()  {
   InputText="$(tr ';' ' '  <<< "$InputText" | tr '$' ' \n' | tr ' ' '\n' | grep -sE '[[:print:]]')" 
 
   if [[ ! $InputText ]]; then 
-    printf "\n\n  ERROR: no input found.  Is input present as a quoted element? \n\n"  
-    show_help ; return 1
+    printf "\n\n  ERROR: no input found.  Is input present as a quoted element? \n\n" >&2
+    show_help >&2 ; return 1
   fi
 
   [[ $FilterString ]] && mapfile -t FilterArr <<< "$(tr ' ' '\n' <<< "$FilterString")"
@@ -203,12 +203,12 @@ float_version_from_string ()  {
 
   if [[ $UseSortV ]] &&  ! sort --help | grep -sq -o 'version-sort' ; then 
     if [[ $NoSortVfallback ]]; then 
-      printf "\n\n  Sorry, 'sort -V' is not available, you need 'jq' to run this script. \n\n"
+      printf "\n\n  Sorry, 'sort -V' is not available, you need 'jq' to run this script. \n\n"  >&2
     else UseSortV= ; fi
   fi
 
   if [[ ! $UseSortV ]] && [[ ! "$(command -v jq)" ]]; then
-    printf "\n\n  Sorry, you need to install 'jq' to run this script. \n\n"
+    printf "\n\n  Sorry, you need to install 'jq' to run this script. \n\n" >&2
   fi
 
   # -gt test data is fairly controllable and always using full grep avoids error fails 
@@ -236,8 +236,8 @@ float_version_from_string ()  {
   [[ $Verbose ]] && { echo "Nums: ($NumsCount)"; echo "$Nums"; echo ;}
 
   if [[ $GTcompare ]] && [[ "$NumsCount" != 2 ]]; then 
-    printf "\n\n  ERROR:  two floating point or semantic version values should be supplied"  
-    show_help ; return 1
+    printf "\n\n  ERROR:  two floating point or semantic version values should be supplied" >&2
+    show_help >&2 ; return 1
   fi
 
   # none found, return false
@@ -381,27 +381,27 @@ float_version ()  {
       -g|--gt)      GTcompare=1 ; shift ;;
       --sort-v)     UseSortV=1 ; shift ;;
       --no-svb)     NoSortVfallback=1 ; shift ;;
-      *)  if [[ "$1" == '-'* ]]; then printf "\n\n  ERROR:  '%s'  not recognised \n\n" "$1" >&2; return 1
-          elif [[ $InputText ]]; then printf "\n\n  ERROR:  QUOTED Input String or Text File Name should be given only once \n\n" ; return 1
+      *)  if [[ "$1" == '-'* ]]; then printf "\n\n  ERROR:  '%s'  not recognised \n\n" "$1" >&2 ; return 1
+          elif [[ $InputText ]]; then printf "\n\n  ERROR:  QUOTED Input String or Text File Name should be given only once \n\n" >&2 ; return 1
           else InputText="$1" ; shift ; fi ;;
     esac
   done
   [[ -e "$InputText" ]] && InputText="$(cat -A "$InputText")"
   InputText="$(tr -cd '[:print:]' <<< "$InputText" | tr ';' ' ' | tr '$' ' ' | tr ' ' '\n' | grep -sE '[[:print:]]')" 
-  [[ ! $InputText ]] && printf "\n\n  ERROR: no input found.  Is '-i' or '-g' the last parameter plus input the last quoted element? \n\n" && return 1
+  [[ ! $InputText ]] && printf "\n\n  ERROR: no input found.  Is '-i' or '-g' the last parameter plus input the last quoted element? \n\n" >&2 && return 1
   [[ $FilterString ]] && mapfile -t FilterArr <<< "$(tr ' ' '\n' <<< "$FilterString")"
   [[ $StartString ]] && mapfile -t StartArr <<< "$(tr ' ' '\n' <<< "$StartString")"
   [[ $DeleteString ]] && mapfile -t DeleteArr <<< "$(tr ' ' '\n' <<< "$DeleteString")" 
   if [[ $ShowMax ]]; then ShowAsStr= ; ShowAsCol= ; elif [[ $ShowAsCol ]]; then ShowAsStr= ; else ShowAsStr=1 ; fi
   if [[ $UseSortV ]] &&  ! sort --help | grep -sq -o 'version-sort' ; then 
-    if [[ $NoSortVfallback ]]; then  printf "\n\n  Sorry, 'sort -V' is not available, you need 'jq' to run this script. \n\n" ; else UseSortV= ; fi
+    if [[ $NoSortVfallback ]]; then  printf "\n\n  Sorry, 'sort -V' is not available, you need 'jq' to run this script. \n\n" >&2 ; else UseSortV= ; fi
   fi
-  if [[ ! $UseSortV ]] && [[ ! "$(command -v jq)" ]]; then printf "\n\n  Sorry, you need to install 'jq' to run this script. \n\n" ; fi
+  if [[ ! $UseSortV ]] && [[ ! "$(command -v jq)" ]]; then printf "\n\n  Sorry, you need to install 'jq' to run this script. \n\n" >&2 ; fi
   [[ $GTcompare ]] && GrepFull=1
   if [[ $GrepFull ]]; then Nums="$(grep -sEo '[0-9]+([.][0-9]+)+([.][0-9]+)?+([.][0-9]+)?+([.][0-9]+)?+([-][[:alnum:]]+)?+([.][[:digit:]]+)?' <<< "$InputText" )"
   else Nums="$(grep -sEo '[0-9]+([.][0-9]+)+([.][0-9]+)?+([.][0-9]+)?+([.][0-9]+)?' <<< "$InputText" )"; fi ;  printf -v Nums "%s\n" "$Nums"
   Nums="$(grep -s '[[:print:]]' <<< "$Nums")" ; NumsCount="$(grep -sc '[[:print:]]' <<< "$Nums")" 
-  if [[ $GTcompare ]] && [[ "$NumsCount" != 2 ]]; then printf "\n\n  ERROR:  two floating point or semantic version values should be supplied" ; return 1 ; fi
+  if [[ $GTcompare ]] && [[ "$NumsCount" != 2 ]]; then printf "\n\n  ERROR:  two floating point or semantic version values should be supplied" >&2 ; return 1 ; fi
   [[ ! $Nums ]] && return 1
   mapfile -t NumArrTemp  <<< "$(tr ' ' '\n' <<< "$Nums")"
   if [[ $ShowAll ]]; then mapfile -t  NumArrSorted <<< "$(printf "%s\n" "${NumArrTemp[@]}")"
