tx full changes to compact; update  readme & bump version

diff --git a/floatversion b/floatversion
--- a/floatversion
+++ b/floatversion
@@ -95,7 +95,7 @@ float_version_from_string ()  {
   -g | -qg | --gt     A > B, returns true/false eg. if fv -g \"A B\"; then .. (.nums or sem ver)  
                       use -v for dev output, normally quiet and allows conditional testing (-qg quieter errors)
   -Q | --quiet        Quieten general error messages, as alternative to using '2>/dev/null'
-                      Use -qc | -qs | -qg  for reduced error output on machine tests (no help notes)
+                      Use -qc | -qs | -qg  for reduced error output on full machine tests (no help notes)
   -v | --verbose      show algorithm sequences (full version only) for problem output.
        --sort-v       use sort -V (if present) in preference to the default jq methods
        --no-svb       no falling back to 'jq' if 'sort -V' is unavailable, show error instead
@@ -156,7 +156,7 @@ fi
       -h|--help)  
         show_help ; return 0 ;;
       -V|--version)
-        CurrentVersion="1.4.0"
+        CurrentVersion="1.4.01"
         printf "\n CurrentVersion: %s" "$CurrentVersion"
         printf "\n\n Checking for updates....   "
         LatestVersion="$(floatversion -M "$(curl -sf --max-time 5 "https://github.com/TuxVinyards/floatversion/releases" | grep 's/tag')" 2>/dev/null)"
@@ -457,53 +457,57 @@ fi
 ##
 
 # COMPACT VERSION, suitable for embedding into other scripts, if preferred  (help and annotation removed)
+#  For quiet, use -Q.  Use of  -qc | -qs | -qg  reduces error output on full machine tests only (no help notes)
 # # NB make sure that locale is set in the main script. See notes at start.
 
 floatversion ()  {
   # floatversion --options  "quoted-input-string-or-text-file" 
   # (c) Alex Genovese - version 1.02.02 (compact) - Usage/Help/Details @ https://github.com/TuxVinyards/floatversion
   local ShowAsStr= ; local ShowAsCol= ; local ShowMax= ; local ShowRev= ; local ShowAll= ; local SortNum= ; local GrepFull= ; local HideErrors=
-  local InputText= ; local Nums= ; local NumsCount= ; local FilterString= ; local StartString= ; local DeleteString= ; local GTcompare=
+  local InputText= ; local Nums= ; local NumsCount= ; local FilterString= ; local StartString= ; local DeleteString= ; local GTcompare=; local GT=
   local UseSortV= ; local NoSortVfallback= ; declare -a NumArrTemp ; declare -a NumArrSorted ; declare -a SelectArrTemp 
   declare -a FilterArr ; declare -a StartArr ; declare -a DeleteArr ; declare -ga fvOutputArr 
   while [[ "$1" ]] ; do
     case "$1" in
-      -Q|--quiet)   HideErrors=1 ; shift ;;
-      -c|-qc|--col)   [[ $1 == "-qc" ]] && HideErrors=1 ; ShowAsCol=1 ; shift ;;
-      -s|-qs|--space) [[ $1 == "-qs" ]] && HideErrors=1 ; SingleSpace=1 ; shift ;;
-      --sort-v)     UseSortV=1 ; shift ;;
+      -Q|--quiet)       HideErrors=1 ;  shift ;;
+      -c|-qc|--col)     ShowAsCol=1 ;   shift ;;
+      -s|-qs|--space)   SingleSpace=1 ; shift ;;
+      --sort-v)         UseSortV=1 ;    shift ;;
       --no-svb)     NoSortVfallback=1 ; shift ;;
-      -r|--rev)     ShowRev=1 ; shift ;;
-      -a|--all)     ShowAll=1 ; shift ;;
-      -n|--num)     SortNum=1 ; shift ;;
-      -f|--full)    GrepFull=1 ; shift ;;
-      -F|--filter)  [[ ! $2 ]] && return 1 ; FilterString="$2" ; shift 2 ;;
-      -S|--start)   [[ ! $2 ]] && return 1 ; StartString="$2" ; shift 2 ;;
-      -D|--delete)  [[ ! $2 ]] && return 1 ; DeleteString="$2" ; shift 2 ;;
+      -r|--rev)     ShowRev=1 ;   shift ;;
+      -a|--all)     ShowAll=1 ;   shift ;;
+      -n|--num)     SortNum=1 ;   shift ;;
+      -f|--full)    GrepFull=1 ;  shift ;;
+      -F|--filter)  [[ ! $2 ]] && return 1 ; FilterString="$2" ;  shift 2 ;;
+      -S|--start)   [[ ! $2 ]] && return 1 ; StartString="$2" ;   shift 2 ;;
+      -D|--delete)  [[ ! $2 ]] && return 1 ; DeleteString="$2" ;  shift 2 ;;
       -M|--max)     ShowMax=1 ; shift ; [[ "$1" == [1-9] || "$1" == [1-9][0-9] ]] && { TopMax="$1"; ShowMax=; shift; } ;;
       -RM)          ShowMax=1 ; RevMax=1 ; shift ; [[ "$1" == [1-9] || "$1" == [1-9][0-9] ]] && { TopMax="$1"; ShowMax=; shift; } ;;
-      -g|--gt)      GTcompare=1 ; shift ;;
-      *)  if [[ "$1" == '-'* ]]; then [[ ! $HideErrors ]] && printf "\n  ERROR:  '%s'  not recognised \n\n" "$1" >&2 ; return 1
-          elif [[ $InputText ]]; then [[ ! $HideErrors ]] && printf "\n  ERROR:  QUOTED Input String or Text File Name should be given only once \n\n" >&2 ; return 1
+      -g|-qg|--gt)  GTcompare=1 ; shift ;;
+      *)  if [[ "$1" == '-'* ]]; then [[ ! $HideErrors ]] && printf "\n  FloatVersion:  '%s'  not recognised \n\n" "$1" >&2 ; return 1
+          elif [[ $InputText ]]; then [[ ! $HideErrors ]] && printf "\n  FloatVersion:  QUOTED Input String or Text File Name Name not found \n\n" >&2 ; return 1
           else InputText="$1" ; shift ; fi ;;
     esac
   done
   [[ -e "$InputText" ]] && InputText="$(cat -A "$InputText")"
   InputText="$(tr -cd '[:print:]' <<< "$InputText" | tr ';' ' ' | tr '$' ' ' | tr ' ' '\n' | grep -sE '[[:print:]]')" 
-  if [[ ! $InputText ]]; then [[ ! $HideErrors ]] && printf "\n  ERROR: no input found.  Is '-i' or '-g' the last parameter plus input the last quoted element? \n\n" >&2 ; return 1 ; fi
+  if [[ ! $InputText ]]; then [[ ! $HideErrors ]] && printf "\n  FloatVersion: Input Data Missing or not found.  \n\n" >&2 ; return 1 ; fi
   [[ $FilterString ]] && mapfile -t FilterArr <<< "$(tr ' ' '\n' <<< "$FilterString")"
   [[ $StartString ]] && mapfile -t StartArr <<< "$(tr ' ' '\n' <<< "$StartString")"
   [[ $DeleteString ]] && mapfile -t DeleteArr <<< "$(tr ' ' '\n' <<< "$DeleteString")" 
   if [[ $ShowMax ]]; then ShowAsStr= ; ShowAsCol= ; elif [[ $ShowAsCol ]]; then ShowAsStr= ; else ShowAsStr=1 ; fi
   if [[ $UseSortV ]] &&  ! sort --help | grep -sq -o 'version-sort' ; then 
-    if [[ $NoSortVfallback ]]; then  [[ ! $HideErrors ]] && printf "\n  Sorry, 'sort -V' is not available, you need 'jq' to run this script. \n\n" >&2 ; else UseSortV= ; fi
+    if [[ $NoSortVfallback ]]; then  [[ ! $HideErrors ]] && printf "\n  FloatVersion: 'sort -V' is not available, you need 'jq' to run this script. \n\n" >&2 ; else UseSortV= ; fi
   fi
-  if [[ ! $UseSortV ]] && [[ ! "$(command -v jq)" ]]; then [[ ! $HideErrors ]] && printf "\n  Sorry, you need to install 'jq' to run this script. \n\n" >&2 ; fi
-  [[ $GTcompare ]] && GrepFull=1
+  if [[ ! $UseSortV ]] && [[ ! "$(command -v jq)" ]]; then [[ ! $HideErrors ]] && printf "\n  FloatVersion: you need to install 'jq' to run this script. \n\n" >&2 ; fi
+  if [[ $GTcompare ]]; then 
+    if [[ $SortNum ]] ; then [[ ! "$(command -v bc)" ]] && printf "\n  FloatVersion: you need to install 'bc' for standard numerical comparisons. \n" >&2 ; GrepFull=
+    else GrepFull=1 ; fi
+  fi
   if [[ $GrepFull ]]; then Nums="$(grep -sEo '[0-9]+([.][0-9]+)+([.][0-9]+)?+([.][0-9]+)?+([.][0-9]+)?+([-][[:alnum:]]+)?+([.][[:digit:]]+)?' <<< "$InputText" )"
   else Nums="$(grep -sEo '[0-9]+([.][0-9]+)+([.][0-9]+)?+([.][0-9]+)?+([.][0-9]+)?' <<< "$InputText" )"; fi ;  printf -v Nums "%s\n" "$Nums"
   Nums="$(grep -s '[[:print:]]' <<< "$Nums")" ; NumsCount="$(grep -sc '[[:print:]]' <<< "$Nums")" 
-  if [[ $GTcompare ]] && [[ "$NumsCount" != 2 ]]; then [[ ! $HideErrors ]] && printf "\n  ERROR:  two floating point or semantic version values should be supplied \n\n" >&2 ; return 1 ; fi
+  if [[ $GTcompare ]] && [[ "$NumsCount" != 2 ]]; then [[ ! $HideErrors ]] && printf "\n  FloatVersion:  TWO floating point or TWO semantic version values should be supplied \n\n" >&2 ; return 1 ; fi
   [[ ! $Nums ]] && return 1
   mapfile -t NumArrTemp  <<< "$(tr ' ' '\n' <<< "$Nums")"
   if [[ $ShowAll ]]; then mapfile -t  NumArrSorted <<< "$(printf "%s\n" "${NumArrTemp[@]}")"
@@ -548,7 +552,9 @@ floatversion ()  {
       fi ; fi
   fi
   if [[ $GTcompare ]]; then 
-    if [[ "${NumArrTemp[0]}" == "${fvOutputArr[-1]}" ]] && [[ "${NumArrTemp[0]}" != "${NumArrTemp[1]}" ]]; then return 0 ; else return 1 ; fi
+    if [[ $SortNum ]]; then [[ "$(bc -l <<< "${NumArrTemp[0]} > ${NumArrTemp[1]}")" == "1" ]] && GT=1
+    else [[ "${NumArrTemp[0]}" == "${fvOutputArr[-1]}" ]] && [[ "${NumArrTemp[0]}" != "${NumArrTemp[1]}" ]] && GT=1 ; fi
+    if [[ $GT ]]; then  [[ $Verbose ]] && { echo "true"; echo ;} ; return 0 ; else [[ $Verbose ]] && { echo "false"; echo ;} ; return 1 ; fi
   elif [[ "${fvOutputArr[*]}" ]] && [[ $ShowAsStr || $ShowAll ]] && [[ ! $ShowAsCol ]]; then 
     if [[ $SingleSpace ]]; then printf "%s " "${fvOutputArr[@]}"; else printf "%s  " "${fvOutputArr[@]}"; fi
   elif [[ "${fvOutputArr[*]}" ]] && [[ $ShowAsCol ]]; then printf "%s\n" "${fvOutputArr[@]}"
