make error control two level & add -qg option

diff --git a/floatversion b/floatversion
--- a/floatversion
+++ b/floatversion
@@ -68,7 +68,7 @@ FvArrFilePath=
 float_version_from_string ()  {
 
 	show_help () {
-    if [[ ! $HideErrors ]]; then
+    if [[ ! $HideErrors  && ! $HideErrorHelp ]] ; then
 	  printf "
   floatversion --options  \"quoted-input-source-or-data\"  
   OR  data | floatversion --options \"optional-additional\" 
@@ -78,8 +78,8 @@ float_version_from_string ()  {
 
   -h | --help         show help 
   -V | --version      show version
-  -c | --col          show list as column instead of string  (-qc quiet)
-  -s | --space        use single spaced string for machine reading (-qs quiet)
+  -c | --col          show list as column instead of string  (-qc quieter errors)
+  -s | --space        use single spaced string for machine reading (-qs quieter errors)
   -r | --rev          show list in reverse order  
   -a | --all          show all extracted values, not just unique 
   -n | --num          sort by standard numbering, not versioning
@@ -92,9 +92,10 @@ float_version_from_string ()  {
   -RM [int]           Outputs the single lowest/earliest value in the list. With integer, as -M but 
                       reverses only the M filter set, not the list, eg. -M 3  > 3 2 1  -RM 3 > 1 2 3
                       also accepts '-r' to reverse a lowest set filter ...
-  -g | --gt           A > B, returns true/false eg. if fv -g \"A B\"; then .. (.nums or sem ver)  
-                      use -v for dev output, normally quiet and allows conditional testing.
+  -g | -qg | --gt     A > B, returns true/false eg. if fv -g \"A B\"; then .. (.nums or sem ver)  
+                      use -v for dev output, normally quiet and allows conditional testing (-qg quieter errors)
   -Q | --quiet        Quieten general error messages, as alternative to using '2>/dev/null'
+                      Use -qc | -qs | -qg  for reduced error output on machine tests (no help notes)
   -v | --verbose      show algorithm sequences (full version only) for problem output.
        --sort-v       use sort -V (if present) in preference to the default jq methods
        --no-svb       no falling back to 'jq' if 'sort -V' is unavailable, show error instead
@@ -128,6 +129,7 @@ fi
   local GrepFull=
   local InputText=
   local HideErrors=
+  local HideErrorHelp=
   local StdIn=
   local Nums=
   local NumsCount=
@@ -175,10 +177,10 @@ fi
       --no-svb)
         NoSortVfallback=1 ; shift ;;
       -c|-qc|--col)
-        [[ $1 == "-qc" ]] && HideErrors=1
+        [[ $1 == "-qc" ]] && HideErrorHelp=1
         ShowAsCol=1 ; shift ;;
       -s|-qs|--space )
-        [[ $1 == "-qs" ]] && HideErrors=1
+        [[ $1 == "-qs" ]] && HideErrorHelp=1
         SingleSpace=1 ; shift ;;
       -r|--rev)
         ShowRev=1 ; shift ;;
@@ -203,15 +205,16 @@ fi
       -RM)
         ShowMax=1 ; RevMax=1 ; shift 
         [[ "$1" == [1-9] || "$1" == [1-9][0-9] ]] && { TopMax="$1"; ShowMax=; shift; } ;;
-      -g|--gt)
+      -g|-qg|--gt)
+        [[ $1 == "-qg" ]] && HideErrorHelp=1
         GTcompare=1; shift ;;
       *) 
         if [[ "$1" == '-'* ]]; then
-          if [[ ! $HideErrors ]]; then  printf "\n  ERROR:  '%s'  not recognised \n" "$1" >&2 ; show_help >&2
+          if [[ ! $HideErrors ]]; then  printf "\n  FloatVersion:  '%s'  not recognised \n\n" "$1" >&2 ; show_help >&2
           fi
           return 1
         elif [[ $InputText ]]; then
-          if [[ ! $HideErrors ]]; then printf "\n  ERROR: QUOTED Input String or Text File Name should be given \n" >&2 ; show_help >&2
+          if [[ ! $HideErrors ]]; then printf "\n  FloatVersion: QUOTED Input String or Text File Name not found \n\n" >&2 ; show_help >&2
           fi
           return 1
         else
@@ -236,9 +239,7 @@ fi
 
   if [[ ! $InputText ]]; then
     if [[ ! $HideErrors ]]; then 
-      { printf "\n  Input data should be piped or presented as a quoted element"
-        printf "\n  To suppress empty pipe errors use '2>/dev/null' \n"
-      } >&2
+      printf "\n  FloatVersion: Input Data Missing or not found. \n\n" >&2
       show_help >&2
     fi
     return 1
@@ -263,12 +264,12 @@ fi
 
   if [[ $UseSortV ]] &&  ! sort --help | grep -sq -o 'version-sort' ; then 
     if [[ $NoSortVfallback ]]; then 
-      printf "\n  Sorry, 'sort -V' is not available, you need 'jq' to run this script. \n"  >&2
+      printf "\n  FloatVersion: 'sort -V' is not available, you need 'jq' to run this script. \n"  >&2
     else UseSortV= ; fi
   fi
 
   if [[ ! $UseSortV ]] && [[ ! "$(command -v jq)" ]]; then
-    printf "\n  Sorry, you need to install 'jq' to run this script. \n" >&2
+    printf "\n  FloatVersion: you need to install 'jq' to run this script. \n" >&2
   fi
 
   # -gt test data is fairly controllable and always using full grep avoids error fails 
@@ -297,7 +298,7 @@ fi
 
   if [[ $GTcompare ]] && [[ "$NumsCount" != 2 ]]; then
     if [[ ! $HideErrors ]]; then 
-      printf "\n  ERROR:  two floating point or semantic version values should be supplied" >&2
+      printf "\n  FloatVersion:  TWO floating point or TWO semantic version values should be supplied \n\n" >&2
       show_help >&2
     fi
     return 1
